
DROP DATABASE blog ;
CREATE DATABASE blog;
USE blog;

CREATE TABLE `user`(
	user_id CHAR(36) NOT NULL,
	first_name VARCHAR(256) NOT NULL,
	last_name VARCHAR(256) NOT NULL,
	created_by VARCHAR(256),
	created_on DATETIME,
	updated_by VARCHAR(256),
	updated_on DATETIME,
	CONSTRAINT pk_user PRIMARY KEY(user_id)
)ENGINE=INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE tag(
	Id INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(256) NOT NULL,
	Description VARCHAR(2000),
	CONSTRAINT pk_tag PRIMARY KEY(Id)
)ENGINE=INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE blog(
	Id INT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(1000) NOT NULL,
	Content TEXT NOT NULL,
	CreatedBy CHAR(36) NOT NULL,
	CreatedOn DATETIME NOT NULL,
	UpdatedOn DATETIME NULL,
	CONSTRAINT pk_blog PRIMARY KEY(Id),
	CONSTRAINT fk_blog_user FOREIGN KEY(CreatedBy) REFERENCES `User`(user_id)
)ENGINE=INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE post(
	Id INT NOT NULL AUTO_INCREMENT,
	Content TEXT NOT NULL,
	CreatedBy CHAR(36) NOT NULL,
	CreatedOn DATETIME NOT NULL,
	UpdatedOn DATETIME NOT NULL,
	PostId INT NOT NULL,
	CONSTRAINT pk_post PRIMARY KEY(Id),
	CONSTRAINT fk_post_user FOREIGN KEY(CreatedBy) REFERENCES `user`(user_id),
	CONSTRAINT fk_post_blog FOREIGN KEY(PostId) REFERENCES blog(Id)
)ENGINE=INNODB DEFAULT CHARSET = UTF8;
