DROP TABLE IF EXISTS data_type;
CREATE TABLE data_type(
	ColTinyInt 		TINYINT,
    ColSmallInt		SMALLINT,
    ColMediumInt	mediumint,
    ColInt			int,
    ColBigInt		bigint,
    ColDecimal		decimal(18,4),
    ColNumeric		numeric(18,4),
    ColFloat		float,
    ColDouble		double,
    ColReal			real,
    ColBit			bit,
    ColDateTime		datetime,
    ColTime			time,
    ColTimeStamp	timestamp,
    ColYear			year,
    ColChar			char(255),
    ColVarChar		varchar(1000),
    ColTinyText		tinytext,
    ColText			text,
	ColMediumText	mediumText,
    ColLongText		longtext,
    ColBinary		binary(255),
	ColVarBinary	varbinary(8000),
    ColTinyBlob		tinyblob,
    ColBlob			blob,
    ColMediumBlob	mediumBlob,
    ColLongBlob		longblob,
    ColJson			json
) Engine=InnoDB default charset=utf8;
